---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # 클러스터 권한 관련된 롤
metadata:
  name: jenkins-admin  # 해당 계정에 대한 권한
  namespace: jenkins
rules:
  - apiGroups: [""]  # 클러스터 내부 API 기능 모두 사용가능
    resources: ["*"] # 클러스터 모든 자원 사용가능
    verbs: ["*"] # 모든 작업 허용
---
# 서비스 계정 만들기
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: jenkins
---
# 서비스 계정에 권한 만들기
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins
